### PR TITLE
Make it pass desktop-file-validate

### PR DESCRIPTION
**Pull request by probonopd**
Reference: https://travis-ci.org/AppImage/AppImageHub/builds/266235424#L547

### CODE REVIEW

**Comment by fathomssen** [comment]
Great, thanks!

**Comment by probonopd** [comment]
Thanks. :+1: Once the new release is out, please ping me over at https://github.com/AppImage/AppImageHub/

**Comment by fathomssen** [comment]
Will do - do you know whether I can merge this commit to the 1.2 branch right from the GitHub frontend? Or do I have to merge it using Git tools?

**Comment by probonopd** [comment]
The easiest is probably to just do the edit by hand:
https://github.com/fathomssen/redtimer/pull/110/files

**Comment by probonopd** [comment]
Please ping me once a new release is out, for https://github.com/AppImage/AppImageHub :-)

**Pull request merged**
