### PR TITLE
1.2

### PR DESCRIPTION
**Pull request by cloudcon**
Translations?
I can translate Brazilian Portuguese.
Put in the user settings and password for the connection with Redmine

### CODE REVIEW

**Comment by fathomssen** [comment]
Hi @cloudcon 

You just created a pull request that would - as far as I see it - merge all changes from 1.1 to 1.2 into branch 1.1. I guess this is not what you intended.

I would be grateful for Portuguese translations. At the moment, the RedTimer does not support translations though. Do you have experience with the Qt translations facilities?

Best regards
Frederick Thomssen

**Comment by cloudcon** [comment]
I'm sorry, I'm still not familiar with GitHub, I just intended to send you a message, but I did not find the location.
About QT Translations, unfortunately I do not have skills in the C ++ area, only in other languages, but would it be very complicated for you to create translation files and the program give Load from them?

**Comment by cloudcon** [comment]
On authentication, I did not find any sites on the system where I put the user and password for Redmine to make the connection. And so it's not working for me.
Windows 10 Platform
Redmine Server: Debian
Redmine Version: 3.4.2

**Comment by fathomssen** [comment]
Hi @cloudcon 

The right way to contact me about RedTimer and report issues is the "Issues" section of this project: https://github.com/fathomssen/redtimer/issues

Please, create the new issues - one for the translations and one for your connection problems.

Best regards
Frederick Thomssen

**Pull request closed without merging**
